name: 🧹Bug Report
description: File a bug report here about the current project your in right now.
title: "[BUG]: "
labels: ["bug"]
assignees: ["imstilljustmatt"]
body:
  - type: markdown
    attributes:
      value: |
        **Hey there!** Thanks for taking your time to file a bug report for our project! 💞
        Your reports are appreciated and can help us improve our projects! 🛠️
        Remember: "Required to fill" properties are marked with a red `*` (asterisk).

  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      description: Give us a brief description of what happened and what should have happened.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior. (while this may be important, you can still optionally add N/A to it)
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: |
        Provide any additional information such as logs, screenshots, likes, scenarios in which the bug occurs so that it facilitates resolving the issue.
